services:
  new-api:
    image: calciumion/new-api:latest
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/data
    restart: unless-stopped

  mysql:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: new-api
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: unless-stopped